### ISSUE TITLE
Windows installer error

### ISSUE THREAD

**Issue by priamai** [idaholab/STIG#88]
Hello,
just installed the windows version and when I launch the application I always get this error.

![image](https://user-images.githubusercontent.com/57333254/206481112-c12815dc-0e3f-4293-a68e-266af656c6c3.png)

Full text below

`Unhandled Promise Rejection
NonError: undefined
    at module.exports.input (C:/Users/robom/AppData/Local/STIG/app-2.0.0/resources/app/node_modules/ensure-error/index.js:14:10)
    at handleError (C:/Users/robom/AppData/Local/STIG/app-2.0.0/resources/app/node_modules/electron-unhandled/index.js:21:10)
    at reason (C:/Users/robom/AppData/Local/STIG/app-2.0.0/resources/app/node_modules/electron-unhandled/index.js:88:4)
    at invokeFunc (C:/Users/robom/AppData/Local/STIG/app-2.0.0/resources/app/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (C:/Users/robom/AppData/Local/STIG/app-2.0.0/resources/app/node_modules/lodash.debounce/index.js:207:14)
    at timerExpired (C:/Users/robom/AppData/Local/STIG/app-2.0.0/resources/app/node_modules/lodash.debounce/index.js:195:14)`

**Comment by priamai** [comment]
Found another issue closing this.
