### ISSUE TITLE
unable to find module

### ISSUE THREAD

**Issue by priamai** [idaholab/STIG#90]
Hi there,
I am on a vanilla Ubuntu installation with OrientDB setup.
I am getting this error:

```
Unhandled Error
Error: Cannot find module './protocol28'
    at Function.Module._resolveFilename (/usr/lib/stig/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Connection.<anonymous> (/usr/lib/stig/resources/app/node_modules/orientjs/lib/transport/binary/connection.js:231:25)
```

**Comment by wrbrant** [comment]
Closing as OrientDB is no longer used
